---
- name: Playing with Debug
  hosts: planetexpress
  gather_facts: true #=> into ansible_facts

 

  vars:
    message1: "Hello world!"

 

  tasks:
    - name: debug with message
      ansible.builtin.debug:
        msg: "This is a message"

 

    - name: debug with message again
      ansible.builtin.debug:
        msg: "This is a message with a variable => {{ ansible_facts.all_ipv4_addresses }}"

 

    - name: debug with message1 variable
      ansible.builtin.debug:
        msg: "This is a message with a variable => {{ message1 }}"

 

    - name: debug with message1 variable
      ansible.builtin.debug:
        var: ansible_facts.keys()
