---
- name: A simple file playbook
  hosts: planetexpress
  gather_facts: yes
  connection: ssh


  tasks:
    - name: make a directory
      ansible.builtin.file:
        path: ~/output/
        state: directory

    - name: user shell module with wildcarding
      ansible.builtin.shell: echo $HOME >> ~/output/path.txt
